apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app-canary
  template:
    metadata:
      labels:
        app: python-app-canary
    spec:
      containers:
        - name: python-app
          image: 868669587970.dkr.ecr.us-east-1.amazonaws.com/python-application:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-canary-service
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
