apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deployer-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "replicasets"]
  verbs: ["create", "get", "list", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: deployer-role-binding
subjects:
- kind: User
  name: "arn:aws:sts::868669587970:assumed-role/GitHubActionsRunnerRole/i-018724c66c8199a5b"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
