name: Hack Canary App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assume IAM Role
        run: |
          aws sts assume-role --role-arn arn:aws:iam::404289934308:role/hackathon-canaryrollout --role-session-name GitHubActionsSession > assumed-role.json
          export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId assumed-role.json)
          export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey assumed-role.json)
          export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken assumed-role.json)

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p Docker running on 64bit Amazon Linux 2023/4.1.0
          eb use Hackcanaryapp
          eb deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2