apiVersion: v1
kind: Namespace
metadata:
  name: canary-deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-1-0-0
  namespace: canary-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
      version: 1-0-0
  template:
    metadata:
      labels:
        app: hello
        version: 1-0-0
    spec:
      containers:
      - name: http-echo
        image: 868669587970.dkr.ecr.us-east-1.amazonaws.com/http-echo:latest
        args:
          - "-text=version 1-0-0"