apiVersion: v1
kind: Service
metadata:
  name: hello-lb
  namespace: canary-deploy
spec:
  selector:
    app: hello
    version: 1-1-0
  ports:
  - port: 80
    targetPort: 5678
    protocol: TCP
    name: http
  type: LoadBalancer