# Use the official Alpine Linux as the base image
FROM alpine:latest

# Set a maintainer label for the image
LABEL maintainer="Mayara Gouveia gb8may@gmail.com"

# Run a command to print "Hello, World!" when a container is started
CMD ["echo", "Hello, World!"]