name: Canary Deployment

on:
  push:
    branches:
      - main

jobs:
  canary-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Assume IAM Role
        run: |
          ROLE_ARN=${{ secrets.EKS_IAM_ROLE_ARN }}
          TEMP_CREDENTIALS=$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name GitHubActions)
          export AWS_ACCESS_KEY_ID=$(echo $TEMP_CREDENTIALS | jq -r .Credentials.AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(echo $TEMP_CREDENTIALS | jq -r .Credentials.SecretAccessKey)
          export AWS_SESSION_TOKEN=$(echo $TEMP_CREDENTIALS | jq -r .Credentials.SessionToken)
        env:
          AWS_DEFAULT_REGION: us-east-1

      - name: Set Up kubectl
        run: |
          aws eks --region us-east-1 update-kubeconfig --name canary-elk-cluster

      - name: Deploy to Canary
        run: |
          kubectl apply -f ./Application/deployment.yaml

      - name: Run Canary Analysis
        run: |
          # Run your canary analysis scripts or tools

      - name: Promote Canary to Stable
        if: success()
        run: |
          kubectl apply -f ./Application/deployment.yaml