name: Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  push-to-ecr:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: ECR Login
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 868669587970.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          sudo docker build -t python-application ./Application/
          sudo docker tag python-application:latest 868669587970.dkr.ecr.us-east-1.amazonaws.com/python-application:latest
          sudo docker push 868669587970.dkr.ecr.us-east-1.amazonaws.com/python-application:latest

      - name: Logout from ECR
        run: |
          sudo docker logout 868669587970.dkr.ecr.us-east-1.amazonaws.com
